apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: extracreditasnmnt
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/Pranathi98/645-hw3-git.git
    targetRevision: HEAD
    path: templates
  destination:
    server: https://kubernetes.default.svc
    namespace: myapp
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
