apiVersion: v1
kind: Service
metadata:
  name: my-service
  labels:
    {{- include "extracreditasnmt.labels" . | nindent 4 }}
spec:
  selector:
    app: myapp
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
