apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    {{- include "extracreditasnmt.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: myapp
    replicas: 2
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: myapp
        image: pranathi2207/swe645-ast3-image-fin
        ports:
        - containerPort: 8080
        